# Generated by Django 3.1.3 on 2021-05-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformareceipt',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
