# Generated by Django 3.1.3 on 2021-06-08 21:27

from django.db import migrations, models
import proforma.models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0003_auto_20210531_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformareceipt',
            name='reference_Number',
            field=models.CharField(default=proforma.models.ProformaReceipt.createproformastandard, max_length=200, null=True),
        ),
    ]
