# Generated by Django 3.1.3 on 2021-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20210407_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanyinformation',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
