# Generated by Django 3.1.3 on 2021-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_comanyinformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanyinformation',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
