# Generated by Django 3.1.3 on 2021-04-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20210407_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanyinformation',
            name='image',
        ),
    ]
