# Generated by Django 3.1.3 on 2021-04-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_remove_comanyinformation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_Percentage', models.FloatField(null=True)),
                ('GET_Fund_Percentage', models.FloatField(null=True)),
                ('NHIL_Percentage', models.FloatField(null=True)),
                ('VAT_Flat_Percentage', models.FloatField(null=True)),
                ('Installation_Retention', models.FloatField(null=True)),
                ('discount_Rate', models.FloatField(null=True)),
                ('Maximum_Discount_Rate', models.FloatField(null=True)),
                ('Commission_Retention', models.FloatField(null=True)),
                ('maximum_Retention', models.FloatField(null=True)),
            ],
        ),
    ]
