# Generated by Django 3.1.3 on 2021-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='othertransactiondefinition',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileinformation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesmaninformation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taxtableinformation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
