# Generated by Django 3.1.3 on 2021-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20210423_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_Rate', models.FloatField(null=True)),
                ('start_Limit', models.FloatField(null=True)),
                ('end_Limit', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
