# Generated by Django 3.1.3 on 2021-05-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_auto_20210506_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankaccountinformation',
            name='account_Number',
            field=models.PositiveIntegerField(max_length=200, null=True),
        ),
    ]
