# Generated by Django 3.1.3 on 2021-05-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20210506_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='name',
        ),
    ]
