# Generated by Django 3.1.3 on 2021-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_remove_servicetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerinformation',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
