# Generated by Django 3.1.3 on 2021-05-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_installerinformation_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcolourinformation',
            name='name',
        ),
    ]
