# Generated by Django 3.1.3 on 2021-05-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_remove_materialcolourinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaninformation',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
