# Generated by Django 3.1.3 on 2021-04-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0002_branchinformation_comanyinformation_companybankaccountinformation_currency_customer_installationchar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_Number', models.CharField(max_length=200, null=True)),
                ('payment_Date', models.DateField()),
                ('value_Date', models.DateField()),
                ('withold_Tax', models.BooleanField()),
                ('branch_id', models.ManyToManyField(to='tools.BranchInformation')),
            ],
        ),
    ]
