# Generated by Django 3.1.3 on 2021-04-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='withold_Tax',
            field=models.BooleanField(default=True),
        ),
    ]
