# Generated by Django 3.1.3 on 2021-04-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_branchinformation_comanyinformation_companybankaccountinformation_currency_customer_installationchar'),
        ('sales', '0002_auto_20210403_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='withold_Tax',
            new_name='post_Dated_Cheque',
        ),
        migrations.AddField(
            model_name='reference',
            name='cheque_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='cheque_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='customer_bank',
            field=models.ManyToManyField(to='tools.BankInformation'),
        ),
        migrations.AddField(
            model_name='reference',
            name='mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Transfer Pay', 'Transfer Pay'), ('Momo', 'Momo')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='receipt_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='withhold_Tax',
            field=models.BooleanField(default=True),
        ),
    ]
