# Generated by Django 3.1.3 on 2021-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210404_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='post_Dated_Cheque',
            field=models.BooleanField(),
        ),
    ]
