# Generated by Django 3.1.3 on 2021-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_branchinformation_comanyinformation_companybankaccountinformation_currency_customer_installationchar'),
        ('sales', '0004_auto_20210404_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='base_Amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='currency',
            field=models.ManyToManyField(to='tools.Currency'),
        ),
        migrations.AddField(
            model_name='reference',
            name='narration',
            field=models.ManyToManyField(to='tools.Narration'),
        ),
        migrations.AddField(
            model_name='reference',
            name='proforma_Number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
