# Generated by Django 3.1.3 on 2021-04-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_remove_comanyinformation_image'),
        ('sales', '0005_auto_20210404_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.customer'),
        ),
    ]
