# Generated by Django 3.1.3 on 2021-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210421_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformareceipt',
            name='charge_Vat',
            field=models.BooleanField(null=True),
        ),
    ]
