# Generated by Django 3.1.3 on 2021-04-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20210421_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformareceipt',
            name='charge_Vat',
        ),
    ]
