# Generated by Django 3.1.3 on 2021-04-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_proformareceipt_charge_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformareceipt',
            name='charge_Vat',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
