# Generated by Django 3.1.3 on 2021-04-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_tax'),
        ('sales', '0013_proformareceipt_charge_vat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesReceipt',
            new_name='MaterialReceipt',
        ),
    ]
