# Generated by Django 3.1.3 on 2021-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_installationpaymentreceipt_pointofsalesreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsalesreceipt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
