# Generated by Django 3.1.3 on 2021-04-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_pointofsalesreceipt_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformareceipt',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
