# Generated by Django 3.1.3 on 2021-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20210422_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformareceipt',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
