# Generated by Django 3.1.3 on 2021-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20210422_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreceipt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pointofsalesreceipt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proformareceipt',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proformareceipt',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
