# Generated by Django 3.1.3 on 2021-04-26 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20210423_0919'),
        ('sales', '0019_auto_20210423_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='cheque_Date',
            field=models.DateTimeField(auto_now_add=True, default='2021-04-26'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='cheque_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='commission_Charged',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='installer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.installerinformation'),
        ),
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='payment_Method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pointofsalesreceipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proformareceipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proformareceipt',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
