# Generated by Django 3.1.3 on 2021-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20210426_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsalesreceipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proformareceipt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proformareceipt',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
