# Generated by Django 3.1.3 on 2021-04-26 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20210426_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofsalesreceipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proformareceipt',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
