# Generated by Django 3.1.3 on 2021-04-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_discounttable'),
        ('sales', '0022_auto_20210426_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.currency'),
        ),
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='customer_bank',
            field=models.ManyToManyField(to='tools.BankInformation'),
        ),
        migrations.AddField(
            model_name='installationpaymentreceipt',
            name='narration',
            field=models.ManyToManyField(to='tools.Narration'),
        ),
        migrations.CreateModel(
            name='CommssionPaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_Number', models.CharField(max_length=200, null=True)),
                ('invoice_Amount', models.FloatField(null=True)),
                ('PFI_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.proformareceipt')),
                ('discount', models.ManyToManyField(to='tools.DiscountTable')),
            ],
        ),
    ]
