# Generated by Django 3.1.3 on 2021-04-27 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_discounttable'),
        ('sales', '0023_auto_20210426_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_Number', models.CharField(max_length=200, null=True)),
                ('invoice_Amount', models.FloatField(null=True)),
                ('invoice_Discount', models.FloatField(null=True)),
                ('initial_Pay', models.FloatField(null=True)),
                ('difference', models.FloatField(null=True)),
                ('maximum_Discount', models.FloatField(null=True)),
                ('maximum_Discount_Paid', models.FloatField(null=True)),
                ('commission_Retained', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recepient_Name', models.CharField(max_length=200, null=True)),
                ('phone_Number', models.CharField(max_length=200, null=True)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Transfer Pay', 'Transfer Pay'), ('Momo', 'Momo')], max_length=200, null=True)),
                ('cheque_Number', models.CharField(max_length=200, null=True)),
                ('cheque_Date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(null=True)),
                ('base_Amount', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('PFI_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.proformareceipt')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.currency')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.customer')),
                ('customer_bank', models.ManyToManyField(to='tools.BankInformation')),
                ('discount', models.ManyToManyField(to='tools.DiscountTable')),
                ('narration', models.ManyToManyField(to='tools.Narration')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_Number', models.CharField(max_length=200, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('choice', models.CharField(choices=[('Bank Pay In', 'Bank Pay In'), ('Expenses', 'Expenses')], max_length=200, null=True)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=200, null=True)),
                ('cheque_Number', models.CharField(max_length=200, null=True)),
                ('account_Number', models.CharField(max_length=200, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.currency')),
                ('customer_bank', models.ManyToManyField(to='tools.BankInformation')),
                ('narration', models.ManyToManyField(to='tools.Narration')),
            ],
        ),
        migrations.DeleteModel(
            name='CommssionPaymentReceipt',
        ),
    ]
