# Generated by Django 3.1.3 on 2021-05-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proforma', '0001_initial'),
        ('sales', '0024_auto_20210427_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionpaymentreceipt',
            name='PFI_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proforma.proformareceipt'),
        ),
        migrations.AlterField(
            model_name='installationpaymentreceipt',
            name='PFI_Number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proforma.proformareceipt'),
        ),
        migrations.DeleteModel(
            name='ProformaReceipt',
        ),
    ]
